name: Build Geonite Latest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: "0 16 * * *"  # Runs every day at midnight UTC+8

env:
  SOLUTION_FILE_PATH: Geonite.sln
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: msbuild -t:Restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build solution
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform="x64" ${{env.SOLUTION_FILE_PATH}}
